---
# defaults to be altered per-host/group
podman_create_host_directories: true
podman_prune_images: true
# https://github.com/linux-system-roles/podman?tab=readme-ov-file#podman_quadlet_specs
podman_quadlet_specs:
  - name: proxy
    file_src: quadlets/proxy.network
  - name: mirror-archlinux-rsync
    template_src: quadlets/mirror/archlinux/rsync.container.j2
  - name: mirror-archlinux-web
    template_src: quadlets/mirror/archlinux/web.container.j2
  - name: mirror
    template_src: quadlets/mirror/root.container.j2
  - name: proxy
    template_src: quadlets/proxy.container.j2

lccr: ghcr.io/rolowilde/lcinfra

proxy_web_image: "{{ lccr }}/proxy-dev:caddy-2.9.1"
proxy_data_volume: /var/local/proxy

mirror_web_image: "{{ lccr }}/mirror-web:caddy-2.9.1"
mirror_root_volume: /var/local/mirror

mirror_archlinux_volume: "{{ mirror_root_volume }}/archlinux"
mirror_archlinux_image: "{{ lccr }}/mirror-archlinux:alpine-3.20.5"
mirror_archlinux_source_url: rsync://mirror.accum.se/mirror/archlinux/
mirror_archlinux_lastupdate_url: https://mirror.accum.se/mirror/archlinux/lastupdate
mirror_archlinux_schedule: '*/22 * * * *'
