---
# defaults to be altered per-host/group
podman_create_host_directories: true
podman_prune_images: true
# https://github.com/linux-system-roles/podman?tab=readme-ov-file#podman_quadlet_specs
podman_quadlet_specs:
  - name: services
    file_src: quadlets/services.network
  - name: blackbox-exporter
    template_src: quadlets/blackbox-exporter.container.j2
  - name: prometheus
    template_src: quadlets/prometheus.container.j2
  - name: grafana
    template_src: quadlets/grafana.container.j2
  - name: rsync-archlinux
    template_src: quadlets/rsync-archlinux.container.j2
  - name: mirror-archlinux
    template_src: quadlets/mirror-archlinux.container.j2
  - name: mirror
    template_src: quadlets/mirror.container.j2
  - name: proxy
    template_src: quadlets/proxy.container.j2

lccr: ghcr.io/rolowilde/lcinfra

blackbox_image: docker.io/prom/blackbox-exporter:v0.25.0

prometheus_image: "{{ lccr }}/prometheus:3.1.0"
prometheus_data_volume: /var/local/prometheus

grafana_image: docker.io/grafana/grafana:11.4.0
grafana_data_volume: /var/local/grafana

proxy_image: "{{ lccr }}/proxy:caddy-2.9.1"
proxy_data_volume: /var/local/proxy

mirror_image: "{{ lccr }}/mirror:caddy-2.9.1"
mirror_root_volume: /var/local/mirror

mirror_archlinux_image: "{{ lccr }}/archlinux:alpine-3.20.5"
mirror_archlinux_volume: "{{ mirror_root_volume }}/archlinux"
mirror_archlinux_source_url: rsync://mirror.accum.se/mirror/archlinux/
mirror_archlinux_lastupdate_url: https://mirror.accum.se/mirror/archlinux/lastupdate
mirror_archlinux_schedule: '*/22 * * * *'
