#!/bin/bash
target=/mirror
lock=/syncrepo.lck

[ ! -d "${target}" ] && mkdir -p "${target}"

exec 9>"${lock}"
flock -n 9 || exit

find "${target}" -name '.~tmp~' -exec rm -r {} +

rsync_cmd() {
	local -a cmd=(rsync -rlptH --safe-links --delete-delay --delay-updates
		"--timeout=600" "--contimeout=60" --no-motd)

	if stty &>/dev/null; then
		cmd+=(-h -v --progress)
	else
		cmd+=(--quiet)
	fi

	"${cmd[@]}" "$@"
}

# if we are called without a tty (cronjob) only run when there are changes
if ! tty -s && [[ -f "$target/lastupdate" ]] && diff -b <(curl -Ls "$SYNCREPO_LASTUPDATE_URL") "$target/lastupdate" >/dev/null; then
	# keep lastsync file in sync for statistics generated by the Arch Linux website
	rsync_cmd "$SYNCREPO_SOURCE_URL/lastsync" "$target/lastsync"
	exit 0
fi

rsync_cmd \
	"${SYNCREPO_SOURCE_URL}" \
	"${target}"

echo "Last sync was $(date -d @$(cat ${target}/lastsync))"
