services:
  web:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${LCINFRA_LETSENCRYPT}:/etc/letsencrypt:ro
      - ${LCINFRA_DHPARAM}:/etc/nginx/dhparam.pem:ro
    environment:
      - TZ=${LCINFRA_TIMEZONE}
    healthcheck:
      test: ["CMD", "curl", "-sSf", "https://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    command: renew
    volumes:
      - ${LCINFRA_LETSENCRYPT:-letsencrypt}:/etc/letsencrypt
      - ${LCINFRA_LETSENCRYPT:-letsencrypt}:/var/lib/letsencrypt

networks:
  default:
    name: proxynet
    driver: bridge
