scrape_configs:
  - job_name: host-node-exporter
    static_configs:
      - targets:
          - host.containers.internal:9100
  - job_name: mirror-archlinux-rsync
    static_configs:
      - targets:
          - mirror-archlinux-rsync:9746
