---
collections:
  - name: community.docker
  - name: community.general
  - name: community.crypto

roles:
  - name: geerlingguy.docker
  - name: robertdebock.cron
  - name: artis3n.tailscale
  - name: linux-system-roles.firewall
