---
collections:
  - name: community.general
  - name: containers.podman
  - name: prometheus.prometheus

roles:
  - name: artis3n.tailscale
  - name: linux-system-roles.firewall
  - name: linux-system-roles.podman
