---
- name: Provision a LinuxCentrs.lv server
  hosts: lc
  become: true
  roles:
    - { role: tuned, tags: tuned }
    - { role: artis3n.tailscale, tags: tailscale }
    - { role: linux-system-roles.firewall, tags: firewall }
    - { role: mirror, tags: mirror }
    - { role: proxy, tags: proxy }
