---
- name: Ensure proxy compose directory
  ansible.builtin.file:
    path: "{{ proxy_project_src }}"
    state: directory
    mode: '0755'

- name: Copy files
  ansible.builtin.copy:
    src: ./
    dest: "{{ proxy_project_src }}"
    directory_mode: '0755'
    mode: '0644'

- name: Generate Diffie-Hellman parameters with the default size (4096 bits)
  community.crypto.openssl_dhparam:
    path: "{{ proxy_dhparam }}"

- name: Get host timezone
  ansible.builtin.command:
    cmd: timedatectl show -p Timezone --value
  register: tdctl_tz
  changed_when: tdctl_tz.rc != 0

- name: Template compose.yml
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ proxy_project_src }}/compose.yml"
    mode: '0644'

- name: Run docker-compose project
  community.docker.docker_compose_v2:
    project_src: "{{ proxy_project_src }}"
    build: always
    state: present

- name: Schedule a certbot renewal every 12 hours
  ansible.builtin.cron:
    name: certbot renewal
    cron_file: lcinfra-proxy-certbot
    user: root
    hour: '*/12'
    job: >-
      docker compose --project-directory {{ proxy_project_src }} run --rm certbot &&
      docker compose --project-directory {{ proxy_project_src }} exec web nginx -s reload
    state: present
