---
- name: Ensure proxy compose directory
  ansible.builtin.file:
    path: "{{ proxy_project_src }}"
    state: directory
    mode: '0755'

- name: Ensure conf directory
  ansible.builtin.file:
    path: "{{ proxy_project_src }}/conf"
    state: directory
    mode: '0755'

- name: Template Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ proxy_project_src }}/conf/Caddyfile"
    mode: '0644'

- name: Template compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ proxy_project_src }}/compose.yml"
    mode: '0644'

- name: Run docker-compose project
  community.docker.docker_compose_v2:
    project_src: "{{ proxy_project_src }}"
    build: always
    recreate: always
    remove_orphans: true
    state: present
