---
- name: Ensure mirror compose directory
  ansible.builtin.file:
    path: "{{ mirror_project_src }}"
    state: directory
    mode: '0755'
  tags: docker

- name: Ensure mirror root directory
  ansible.builtin.file:
    path: "{{ mirror_root }}"
    state: directory
    mode: '0755'
  tags: docker

- name: Copy Caddyfile
  ansible.builtin.copy:
    src: Caddyfile
    dest: "{{ mirror_project_src }}"
    directory_mode: '0755'
    mode: '0644'
  tags: docker

- name: Include mirror tasks
  ansible.builtin.include_tasks:
    file: "{{ mirror }}.yml"
  loop: "{{ mirror_list }}"
  loop_control:
    loop_var: mirror
  tags: docker
