---
- name: Ensure mirror compose directory
  ansible.builtin.file:
    path: "{{ mirror_project_src }}"
    state: directory
    mode: '0755'

- name: Ensure mirror root directory
  ansible.builtin.file:
    path: "{{ mirror_root }}"
    state: directory
    mode: '0755'

- name: Copy files
  ansible.builtin.copy:
    src: ./
    dest: "{{ mirror_project_src }}"
    directory_mode: '0755'
    mode: '0644'

- name: Template compose.yml
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ mirror_project_src }}/compose.yml"
    mode: '0644'

- name: Run docker-compose project
  community.docker.docker_compose_v2:
    project_src: "{{ mirror_project_src }}"
    build: always
    state: present

- name: Schedule a sync for each mirror every random minute
  ansible.builtin.cron:
    name: "{{ mirror }} repo sync"
    cron_file: lcinfra-mirror-sync
    user: root
    minute: "{{ 60 | random }}"
    job: docker compose --project-directory {{ mirror_project_src }} exec {{ mirror }} bash /sync
    state: present
  loop: "{{ mirror_list }}"
  loop_control:
    loop_var: mirror
