---
- name: Install and configure Tailscale
  ansible.builtin.include_role:
    name: artis3n.tailscale
  # tailscale_authkey required!

- name: Configure firewall
  ansible.builtin.include_role:
    name: linux-system-roles.firewall
  vars:
    firewall:
      - # default zone
        service: [ssh, cockpit, dhcpv6-client]
        state: disabled

      - interface: tailscale0
        zone: dmz
        state: enabled

      - zone: dmz
        service: [ssh, cockpit]
        state: enabled
