---
# vagrant default machine host vars

# skipped in vagrantfile
tailscale_authkey: null

# prevent syncing
mirror_archlinux_schedule: '0 0 29 2 1'

# https://github.com/linux-system-roles/firewall#examples-of-options
firewall:
  - previous: replaced
  - port: 80/tcp
    state: enabled
  - port: 443/tcp
    state: enabled
  - port: 443/udp
    state: enabled
  - port: 3000/tcp
    state: enabled
