FROM alpine:3.20.5

LABEL org.opencontainers.image.source=https://github.com/rolowilde/lcinfra

RUN apk add --no-cache \
    bash \
    tzdata \
    supercronic \
    curl \
    rsync

COPY entrypoint.sh /

VOLUME [ "/data" ]

ENTRYPOINT [ "/entrypoint.sh" ]
