services:
  root:
    build: .
    image: nginx-mirror:latest
    volumes:
      - ${LCINFRA_MIRROR_ROOT}:/mirror:z,ro
    environment:
      - TZ=${LCINFRA_TIMEZONE}
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  archlinux:
    build: .
    image: nginx-mirror:latest
    volumes:
      - ${LCINFRA_MIRROR_ROOT}/archlinux:/mirror:Z
      - ./archlinux/sync:/sync:Z,ro
    environment:
      - TZ=${LCINFRA_TIMEZONE}
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped

networks:
  default:
    name: mirror_backend_net
    driver: bridge
