services:
  archlinux:
    build: .
    image: nginx-mirror:latest
    volumes:
      - ${LCINFRA_MIRROR_ROOT}/archlinux:/mirror:Z
      - ./archlinux/sync:/sync:ro
    environment:
      - TZ=${LCINFRA_TIMEZONE}
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  default:
    name: mirror_backend_net
    driver: bridge
