---
- name: Generate Diffie-Hellman parameters with the default size (4096 bits)
  community.crypto.openssl_dhparam:
    path: "{{ proxy_dhparam }}"

- name: Get host timezone
  ansible.builtin.command:
    cmd: timedatectl show -p Timezone --value
  register: tdctl_tz
  changed_when: tdctl_tz.rc != 0

- name: Create .env file
  ansible.builtin.copy:
    dest: "{{ proxy_project_src }}/.env"
    mode: '0400'
    content: |
      TZ={{ tdctl_tz.stdout }}
      LCINFRA_LETSENCRYPT={{ proxy_letsencrypt }}
      LCINFRA_DHPARAM={{ proxy_dhparam }}

- name: Run docker-compose project
  community.docker.docker_compose_v2:
    project_src: "{{ proxy_project_src }}"
    state: present

- name: Schedule a certbot renewal every 12 hours
  ansible.builtin.cron:
    name: certbot renewal
    cron_file: docker-proxy-certbot
    user: root
    hour: '*/12'
    job: >-
      docker compose -p proxy run --rm certbot &&
      docker compose -p proxy exec web nginx -s reload
    state: present

- name: Enable http and https service in default zone
  ansible.builtin.include_role:
    name: linux-system-roles.firewall
  vars:
    firewall:
      - service: [http, https]
        state: enabled
