---
- name: Generate Diffie-Hellman parameters with the default size (4096 bits)
  community.crypto.openssl_dhparam:
    path: "{{ proxy_dhparam }}"

- name: Get host timezone
  ansible.builtin.command:
    cmd: timedatectl show -p Timezone --value
  register: tdctl_tz
  changed_when: tdctl_tz.rc != 0

- name: Run docker-compose project
  community.docker.docker_compose_v2:
    project_src: "{{ proxy_project_src }}"
    state: present
  environment:
    LCINFRA_TIMEZONE: "{{ tdctl_tz.stdout }}"
    LCINFRA_LETSENCRYPT: "{{ proxy_letsencrypt }}"

- name: Copy crontab
  ansible.builtin.copy:
    remote_src: true
    src: "{{ proxy_project_src }}/crontab"
    dest: "/etc/cron.d/docker-proxy"
    mode: '0644'
